title: Lab Notebook
author:
  name: Pierre Padilla Huamantinco
  email: pgpadilla@uc.cl
description: Institute for Biological and Medical Engineering

theme: minima

header_pages:
  - about.md

minima:
  skin: dark
